### ISSUE TITLE
Switch off "Run on save" during rebase

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#103]
When I did a rebase in a repo (rebasing 80 commits) the Pester Test Adapter tried to run all tests for each commit. Clicking on "Pester" down in the taskbar disable that, but it then added a entry to the workspace settings.psd1 which "messed up" the rebase since now the settings file was unstaged, so the rebase could not continue since it was not staged. Staging it would make it part of a commit which I didn't want. 

I would like an option to disable "Run on save" in the user settings instead of workspace settings, preferably so that I do not need to manually add the value to the user settings file. 🙂 

Just a thought. Would it be possible to add so that a longer click raises a menu where it possible to choose between user and workspace?

**Comment by JustinGrote** [comment]
@johlju run on save is now not active by default, you have to enabled it using the watcher button in the UI, so now this shouldn't be an issue.
