### ISSUE TITLE
When renaming tests the old one linger 

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#105]
I wrongly named a Describe-block 'SqlEndpoint...', when renaming it correctly it did not disappear from the test explorer. This might be solved by issue #102 but would rather see that it be a refresh on per test file basis not the entire test explorer (if it works). But of course, depends how quick it is to refresh. 🙂 

The "yellow" one is the old one that should have been removed since the test is no longer in the file. The new (correct) one is right beneath (and "green")  

![image](https://user-images.githubusercontent.com/7189721/158013887-349f5b92-6f88-4efb-b6f0-1f6b5f03e4f1.png)

**Comment by JustinGrote** [comment]
Thanks, yeah they usually get cleaned up correctly but sometimes not especially if changes are being made fast, it has to do with the fact that I read in the delta test changes and try to sync rather than wipe the whole test list and start over (that kills test history), it's high on my priority list to find a middle ground in this regard.

**Comment by JustinGrote** [comment]
@johlju the latest prerelease now implements the refresh button if you end up in this situation again as a stopgap until I make the delta test detection smarter.

**Comment by johlju** [comment]
A refresh button will work a long way. Would be great if it was possible for the adapter to compare current test blocks against already found test blocks and remove/add and differences, in that case I can happily take that and metadata is removed, for example if a describe or context block is changed.

**Comment by JustinGrote** [comment]
@johlju that's in the plan, keeping it performant is the tricky part.

**Comment by JustinGrote** [comment]
Fixed 9bc01d5041b21e4b85e5348b95119f9064c7c1ff
