### ISSUE TITLE
Configuration setting for Pester path

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#108]
Could we add a configuration setting `PesterModulePath` so it can be specified relative to the project path where the Pester module is located, and so Pester Test Adapter does not assume it is in `$env:PSModulePath`?

**Comment by JustinGrote** [comment]
I can't say I will make this a priority since you can do it as part of your discovery or test run phase, other than if you want to use a custom version of pester not already on your psmodulepath. I'll put it on the to-do stack though :)

**Comment by johlju** [comment]
I’m happy you put it on the back log. Thank you. 😊 Wish I could help but don’t know where to start. 😊

Some more information, that you probably already know. The problem is that the Pester Test Adapter adapter do not work unless it has Pester in the PSModulePath, if Pester is not available it will not run discovery since it does this prior to discovery:

https://github.com/pester/vscode-adapter/blob/0bae405e6420020af4c5aed70b758d62f5d5d7d6/Scripts/PesterInterface.ps1#L472

with a configuration option we could import the Pester module from a custom relative path so that a user does not need to install the Pester module in a PSModulePath. 

This will help us since our pipeline is using PSDepend that downloads the (Pester module) version specified in a configuration file to a relative path to the local repository root.
