### ISSUE TITLE
"Run Tests" miscounts, gets stuck "running", though "Show Output" shows "Complete".

### ISSUE THREAD

**Issue by ziesemer** [pester/vscode-adapter#113]
Testing against https://github.com/ziesemer/ad-privileged-audit/tree/b0444d6484f7e7b50c67831ab3ddb65802c5ff6d for this report.

The VSC UI is stuck on:
![image](https://user-images.githubusercontent.com/1887649/159725287-312bc553-35b6-4dea-98ca-20a3bd5ba52c.png)
in the "Testing" pane and 
![image](https://user-images.githubusercontent.com/1887649/159725353-129ecf27-39d7-4895-b0d9-c3540a8724ed.png)
in the status bar.

Clicking on "Show Output" to display the "Test Output" starts with:
```
Starting discovery in 3 files.
Discovery found 60 tests in 70ms.
Running tests.
```
... and finishes with:
```
[+] ***\ad-privileged-audit\Tests\AD-Privileged-Audit.Tests.ps1
 4s (3.31s|650ms)
[+] ***\ad-privileged-audit\Tests\Write-Log.Tests.ps1
 65ms (30ms|29ms)
[+] ***\ad-privileged-audit\Tests\DistinguishedNameParser.Tests.ps1
 259ms (96ms|156ms)
Tests completed in 4.36s
Tests Passed: 60,
Failed: 0,
Skipped: 0

NotRun: 0
```

After then clicking "Cancel Test Run", the "Testing" UI updates to:
![image](https://user-images.githubusercontent.com/1887649/159726234-b5df90b3-5076-4845-9424-39de99ba088c.png)
... and the "Test Output" further appends:
`> Test run finished at 3/23/2022, 9:44:43 AM <`

The adapter seems to be getting confused in the count of tests, as I never see the 75 number outside of use of the adapter.  Furthermore, the difference of 15 (75-60) seems to be the number of branch nodes in the discovered tree - accounting for the number of "Describe" and "Context" blocks, as well as for each additional test file other than the first.

Pester Tests version:
```
Name: Pester Tests
Id: pspester.pester-test
Description: Enables you to run PowerShell Pester tests using the VSCode testing feature
Version: 2022.2.0
Publisher: Pester
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=pspester.pester-test
```
VSC version: 1.65.2.

**Comment by JustinGrote** [comment]
Thanks for the report! Yes there are some issues with the way runs are handled and pre-empted that can cause it to be stuck. A "reload window" should sort this out, and I plan to implement the new refresh button UI (#102) to do something similar without having to reload the new window.

**Comment by coolhome** [comment]
I have two test files, each with a single describe. The file and describe become a yellow clock icon and never successful. Not having luck with anything either. Strangely running the file as Debug from the testing panel will show all green 🤯

**Comment by philipmgrant** [comment]
> I have two test files, each with a single describe. The file and describe become a yellow clock icon and never successful. Not having luck with anything either. Strangely running the file as Debug from the testing panel will show all green 🤯

The same for me, but I hadn't thought of doing it in Debug mode, and that works great - thanks for the tip!

When not running in Debug mode, the status of the "leaf nodes" (individual tests) doesn't get propagated up to their parents (the Describes, Contexts and files).  That doesn't seem to be affected by refreshing the tests, restarting VSC or even rebooting the machine.

**Comment by bbi-willemtoorenburgh** [comment]
I'm experiencing this as well on the latest version of VSCode and the Pester and Powershell plugins. I can also corroborate that running the tests in debug mode does not present this behaviour.

**Comment by JustinGrote** [comment]
Hey thanks all for noting, I know it's a long standing problem but it requires a difficult refactoring of how events are streamed and collected from the Pester module to fix and my focus is on ModuleFast at the moment. I'll label it "help wanted" but it has a high difficulty bar to clear (you need expert knowledge of Typescript, node.js streams, named pipes, and intimate Powershell and Pester details)

**Comment by JustinGrote** [comment]
Hey everyone,

I've had some time to work on this again. I've identified an issue when you initiate a new test run while another is going, that things don't get properly cancelled and cleaned up between test runs. There is a new API for a stop button that implements a `CancellationToken` that I plan to implement for full cancellation and cleanup for interruption of runs that should resolve this issue. Stay tuned.

**Comment by JustinGrote** [comment]
@ziesemer this should be fixed by https://github.com/pester/vscode-adapter/pull/151 in the latest prerelease (2023.6.4), can you give it a test?

**Comment by ziesemer** [comment]
I assume you mean 2023.6.2.  Again, this looks fantastic - and the original test case here is now passing without issue and as expected.  Thank you!

**Comment by ziesemer** [comment]
Closing as per above.  Thank you!
