### ISSUE TITLE
Extension requires reload to activate after first tests.ps1 file

### ISSUE THREAD

**Issue by fflaten** [pester/vscode-adapter#122]
The current activationevent for *.tests.ps1 in the workspace doesn't trigger on new file. You need to reload windows after the first test-file exists. Any way to make it look again on file creation and/or rename?

**Comment by fflaten** [comment]
Probably depends on microsoft/vscode#28122.
Maybe mention reload-requirement in the readme while we wait? 🙂

**Comment by JustinGrote** [comment]
@fflaten good tip. As an alternative, they now have an option to lazy-load an extension, so we could lazy-load and have a minimal filesystem watcher.

**Comment by JustinGrote** [comment]
@fflaten warning added to README in 6e64003b562606c829128edd19374a2226f11a5c

**Comment by fflaten** [comment]
Thanks. Close issue or leave open until vscode has a new event or something?

**Comment by JustinGrote** [comment]
Leaving open for the lazy load activation to be implemented.
