### ISSUE TITLE
Restart Test Shell

### ISSUE THREAD

**Issue by abbgrade** [pester/vscode-adapter#124]
When testing binary modules, it's important to be able to kill and recreate the shell process, that runs the tests, since DLLs cannot be unloaded and if they are loaded the file is locked and a rebuild will fail.

**Comment by JustinGrote** [comment]
@abbgrade Thanks! This is a dupe of https://github.com/pester/vscode-adapter/issues/102

**Comment by JustinGrote** [comment]
@abbgrade also have you tried this setting?
![image](https://user-images.githubusercontent.com/15258962/161636398-d5b152f9-6838-4d28-8ced-2e86e4ca0114.png)
