### ISSUE TITLE
`pester.testFilePath`: How to exclude Directory?

### ISSUE THREAD

**Issue by schittli** [pester/vscode-adapter#127]
Good evening

**Thank you very much for your great work,**
I hope that all your work is not mainly done in your spare time and Microsoft pays your wages, because only thanks to Pester Microsoft is able to ensure the quality of endless PowerShell Modules.

Unfortunately, VS Code uses Glob Patterns, which got the last update in 1975, and this is exactly how the configuration of `pester.testFilePath` feels: Like concepts of the last millennium... 😞 

**The question:**
Is it possible to easily extend the default pattern `**/*.[tT]ests.[pP][sS]1` so that the two Directories are excluded?:
```
\exludeDir1\**
\exludeDir2\**
```
I have tested many glob examples, but none of them work. 

**If it is not possible in general or the syntax is a nightmare:**
Could you please think about adding something like this:?
`"pester.testFilePathExcludes"`

Thanks a lot, kind regards,
Thomas

**Comment by JustinGrote** [comment]
Sorry it took so long to respond to this. Test discovery uses glob because most people are familiar with vscode glob and most filewatcher tools require globs to operate. I may consider adding regex in the future but you should be able to exclude with `!excludeDir1\**` with current implementation.

**Comment by JustinGrote** [comment]
@schittli have you tried the `files.exclude` setting? That should globally exclude files from searches as well

**Comment by JustinGrote** [comment]
Closing until more info is provided.
