### ISSUE TITLE
`powershell.pester.codeLens`: Unfortunately, the property name does not say what it does

### ISSUE THREAD

**Issue by schittli** [pester/vscode-adapter#128]
Good evening

I am trying to understand a bug in a complex Pester project and stumbled upon the property `powershell.pester.codeLens`.
It is a pity that the property name was not chosen so that the name explains what we change if we modify it.

Therefore, I have this question:
What is `powershell.pester.codeLens` doing?
If it is 'true', 
- does Pester replace code lens?
- does Pester disable code lens?
- does Pester results take precedence over code lens?
- does it just hide code lens in VS Code?
- ...

Thanks a lot for any light 😃 
kind regards, Thomas

**Comment by johlju** [comment]
When it is set to true, or not configured, it will enable the code lens "Run test | Debug test" above Describe-, Context- and It-blocks. Works best with Pester 5.

![image](https://user-images.githubusercontent.com/7189721/202431472-85379575-1883-45d8-a867-92178742d5f3.png)
