### ISSUE TITLE
Button "Go To Test" goes to wrong file, and file has wrong number of code lenses (green checkmarks)

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#131]
There seems to an issue with how the test files describe-, context, and it-blocks are calculated as can see on the below output. 
Opening the test file for test script file `Assert-RequiredCommandParameter.Tests.ps1" takes me to the wrong test script file `Test-DscParameterState.Tests.ps1`. 

![PesterTestAdapter-issue#new](https://user-images.githubusercontent.com/7189721/210064887-7f323790-10e6-440f-b779-928deb1b0e7a.gif)

It can also be seen that the test file got a lot of the code lenses (correct name for the green checkmarks?) that should not be seen in this file. 

![PesterTestAdapter-issue#new2](https://user-images.githubusercontent.com/7189721/210065763-6f23bb4e-3e2e-4e57-bb1c-8db115eb6eca.gif)

**Comment by JustinGrote** [comment]
Fixed 3b9982c004ab1c54d441078aa0f3eca4ab21abf5
