### ISSUE TITLE
🐛 Unexpanded Test Files do not update status if "Run All" is clicked

### ISSUE THREAD

**Issue by AlonGvili** [pester/vscode-adapter#14]
![image](https://user-images.githubusercontent.com/34351424/128702653-6a48fba2-156f-4842-9703-46a4877ff9dd.png)

also when the tests are in the tree view and you click on to run all tests, its only mark the tests that are currently visible in the list as pass or failed, even if you scroll down the list all the others stay gray
and when I click on one test from the list on view file 
![image](https://user-images.githubusercontent.com/34351424/128703663-11fdb76e-c176-4192-b05f-f723a4d91bc8.png)

**Comment by JustinGrote** [comment]
@AlonGvili thanks, I imagine there's a lot of performance issues with large test suites at the moment, I've only done small-scale testing. Can you provide me your repo for reference so I can test against it?

**Comment by AlonGvili** [comment]
> @AlonGvili thanks, I imagine there's a lot of performance issues with large test suites at the moment, I've only done small-scale testing. Can you provide me your repo for reference so I can test against it?

https://github.com/AlonGvili/pwshchakraui

**Comment by JustinGrote** [comment]
@AlonGvili this is a known issue if you haven't expanded a test file before clicking "run all". I used to have a warning in there but pulled it out. This is fixable and on the to-do list, but if you expand the tests first everything should work fine. I was able to run all your tests without issue in PS7 (lots of test-level errors but they ran 😁).

There's several UI issues around "clicking too fast" and things not refreshing after multiple runs as well, those will get cleaned up.

**Comment by AlonGvili** [comment]
> @AlonGvili this is a known issue if you haven't expanded a test file before clicking "run all". I used to have a warning in there but pulled it out. This is fixable and on the to-do list, but if you expand the tests first everything should work fine. I was able to run all your tests without issue in PS7 (lots of test-level errors but they ran 😁).
> 
> There's several UI issues around "clicking too fast" and things not refreshing after multiple runs as well, those will get cleaned up.

LOL,13 tests failed its a lot?, maybe you can add expand all button...,

**Comment by JustinGrote** [comment]
@AlonGvili I have no control over the UI of the test adapter, that'd have to be submitted as a vscode enhancement.

For me pretty much every test failed with `-encoding parameter not found` but I was running it on PS7 :)

**Comment by AlonGvili** [comment]
> @AlonGvili I have no control over the UI of the test adapter, that'd have to be submitted as a vscode enhancement. My planned fix was that if a test file is called to be run, if it hasn't been "resolved" (expanded) then resolve it first.
> 
> For me pretty much every test failed with `-encoding parameter not found` but I was running it on PS7 :)

me too 7.1.3

**Comment by JustinGrote** [comment]
So I tried fixing this but I ended up with a race condition with the new debounce method, I'll need to rearchitect and rewire some stuff in how tests are discovered to resolve this.
