### ISSUE TITLE
vscode 1.77 causes extension to fail to load

### ISSUE THREAD

**Issue by Nieko** [pester/vscode-adapter#140]
In output window with Extension Host the following is seen:

------------
[error] Activating extension pspester.pester-test failed due to an error:
[error] TypeError: Cannot redefine property: prepareStackTrace
	at Function.defineProperty (<anonymous>)
	at [redacted]\extension.js:5:287
[redacted]
	at async Promise.all (index 0)
------------

Rolling back to version 1.76 has fixed the issue on two of two machines tested so far. Appears to be an issue with vscode-adapter rather than vscode itself as has not affected any other extensions I have installed

**Comment by SRoomsCode** [comment]
Same issue with VSCode 1.77.0 and 1.77.1.
When rolling back to VSCode 1.76.2 the Test Explorer and Extension work properly.

**Comment by JustinGrote** [comment]
This should be fixed now, please try the latest release, I'll close this issue in 1 week if no additional feedback is seen.

**Comment by SRoomsCode** [comment]
Thank you.
It look like working as before 👍 
Tested with VSCode Version 1.77.3

**Comment by luma-sb** [comment]
Confirmed on 1.77.3 here as well - tests are listed in explorer and runnable again. :clap:

**Comment by JustinGrote** [comment]
Thanks all!
