### ISSUE TITLE
'Run Tests' fails when testing functions using -Verbose:$VerbosePreference on cmdlet calls

### ISSUE THREAD

**Issue by asa-marshall-spinen** [pester/vscode-adapter#144]
# 'Run Tests' fails when testing functions using -Verbose:$VerbosePreference on cmdlet calls

## Summary

When running tests on functions that contain cmdlet calls that pass through the $VerbosePreference variable to the -Verbose parameter, the tests will fail reporting this error:

`Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter' required by parameter 'Verbose'.`

This behavior only occurs when selecting 'Run Tests' from the extension or by selecting 'Run Test' on individual tests relevant to the function being tested. All tests will pass when using 'Debug Tests' from the extension or by manually running `Invoke-Pester` from the terminal.

No custom configurations have been made to the Pester Tests extension.

The Pester tests themselves do not interact with the $VerbosePreference variable or the -Verbose common parameter.

When removing -Verbose:$VerbosePreference from functions being tested, all tests will pass normally.

## Expected Behavior

All tests should pass.

## Actual Behavior

Here is a sample function and a set of unit tests to help explain the problem:

### Sample Function

```PowerShell
function Remove-LogFile {
    <#
        .SYNOPSIS
        Removes a specified number of log files from a specified path.

        .DESCRIPTION
        This function removes a specified number of log files with a .log extension from the specified path. 
        By default, the function removes 10 log files, but this can be adjusted using the Count parameter.

        .PARAMETER Path
        Specifies the path where the log files should be removed from.

        .PARAMETER Count
        Specifies the number of log files to remove. Default value is 10.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory = $true)][string]$Path,
        [int32]$Count = 10
    )

    # Check if path exists
    if (!(Test-Path -Path $Path)) {
        Throw "Path does not exist."
    }

    # Get log files specified by count
    $LogFiles = (Get-ChildItem -Path $Path | Where-Object Extension -eq ".log" | Sort-Object -Property CreationTime | Select-Object -First $Count)

    # Iterate through log files and remove
    $LogFiles | ForEach-Object {
        Remove-Item -Path $_.FullName -Verbose:$VerbosePreference -WhatIf:$WhatIfPreference # FIXME: Pester Tests extension fails when running this line
    }
}
```

### Shortened Sample Pester Test File

```PowerShell
Describe "Remove-LogFile Unit Tests" -Tag "Unit" {
    Context "Using TestDrive:\" {

        BeforeAll {
            # dotsource function into memory
            . (Get-Item -Path "$PSScriptRoot\..\..\SampleModule\function\Remove-LogFile.ps1").FullName
        }

        BeforeEach {
            Get-ChildItem -Path $TestDrive -Recurse | Remove-Item -Force
        }

        # Test will PASS since there is no interaction with a cmdlet that uses -Verbose:$VerbosePreference
        It "Throws if specified path does not exist" {
            { Remove-LogFile -Path "$TestDrive\NonExistantFolder" } | Should -Throw
        }

        # Test will FAIL because of interaction with Remove-Item cmdlet with parameter -Verbose:$VerbosePreference
        It "Removes a specified amount of files" {
            for ($i = 0; $i -lt 5; $i++) {
                New-Item -Path $TestDrive -Name "TestFile$i.log" -ItemType File -Value "Test Content"
            }

            (Get-ChildItem -Path $TestDrive) | Should -HaveCount 5
            Remove-LogFile -Path $TestDrive -Count 4
            (Get-ChildItem -Path $TestDrive) | Should -HaveCount 1
        }
    }
}
```

### Expected Results

When selecting 'Run Tests' from the Pester Tests extension, all tests should pass.

### Actual Results

When selecting 'Run Tests' from the Pester Tests extension, the second test shown above, "Removes a specified amount of files", fails with the error:

`Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter' required by parameter 'Verbose'.`

The error is correlated with the following cmdlet call in the sample function shown above:

`Remove-Item -Path $_.FullName -Verbose:$VerbosePreference -WhatIf:$WhatIfPreference`

## Possible Solutions

Adding a custom configuration to bypass the `Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter' required by parameter 'Verbose'.` error is acceptable, but there should be a way to test functions using cmdlets that pass through the $VerbosePreference variable to the -Verbose parameter.

There also could be a simple type assignment error in the way the Pester Tests extension is invoking Pester.

If this behavior is intended, and there is a way to suppress this type conversion error, please let me know.

Thanks!

**Comment by asa-marshall-spinen** [comment]
After looking through the source code for this extension, I may have found the source of this issue and **a possible solution**.

In vscode-adapter/Scripts/PesterInterface.ps1, lines 24-26 manually set Action Preference variables like this:
```PowerShell
$VerbosePreference = 'SilentlyContinue'
$WarningPreference = 'SilentlyContinue'
$DebugPreference = 'SilentlyContinue'
```

Instead of assigning strings, strictly type the variables to System.Management.Automation.ActionPreference like so:
```PowerShell
$VerbosePreference = [System.Management.Automation.ActionPreference]'SilentlyContinue'
$WarningPreference = [System.Management.Automation.ActionPreference]'SilentlyContinue'
$DebugPreference = [System.Management.Automation.ActionPreference]'SilentlyContinue'
```

**Comment by JustinGrote** [comment]
Yeah I trip up on that mistake a lot :). I'll see if I can get it resolved in the next couple weeks but my spare time is really tied up  prepping for PSConfEU ATM.

**Comment by JustinGrote** [comment]
@asa-marshall-spinen I changed how the interface works so that suppressing these is no longer required and I removed those lines, I will close for now but reopen if you still have the issue.
