### ISSUE TITLE
Fails to run or complete discovery under Windows PowerShell 5

### ISSUE THREAD

**Issue by Nieko** [pester/vscode-adapter#152]
All functions past discovery of testing files, i.e. *.tests.ps1, fail with the same exception:

System.Management.Automation.RuntimeException: Invoking step Start failed:
Result 1 - Error 1:The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a 
script block, or
a CommandInfo object.
At C:\Program Files\WindowsPowerShell\Modules\Pester\5.5.0\Pester.psm1:1788 char:19
                 & $p.$Step @ctx

- Workspace Powershell configured to WindowsPowerShell via "powershell.powerShellDefaultVersion" and "terminal.integrated.profiles.windows". `$PSVersionTable` in Terminal confirms Windows Desktop edition 5.1.x
- Checked against Powershell Extension both forced into Windows Powershell Edition and not forced
- Running pester via vscode terminal / shell `invoke-pester` runs fine with no error
- Confirmed bug on three machines

Appears to be the injection of Pester Tests functionality as a pester plugin that is failing

**Comment by Nieko** [comment]
If you change the plugin handling in pester.psm1 to be "aware" of the injector hack by replacing
$plugins.Add((Get-RSpecObjectDecoratorPlugin))

with say another hack:

$rspecPlugin = (Get-RSpecObjectDecoratorPlugin)

            if($rspecPlugin.Count) {
                foreach($subPlugin in $rspecPlugin) {
                    $plugins.Add($subPlugin)
                }
            } 
            else {
                $plugins.Add($rspecPlugin)
            }

The plugin stops failing; which should at least indicate this is the culprit (or near to it)

**Comment by JustinGrote** [comment]
Can you try the latest prerelease? We have a private api to use rather than a hack now that shoukd fix this.

**Comment by Nieko** [comment]
> Can you try the latest prerelease? We have a private api to use rather than a hack now that shoukd fix this.

Just tried the pre-release: works fine now. Thank you.
