### ISSUE TITLE
Don't ask again option in disable codelens notification doesn't work

### ISSUE THREAD

**Issue by fflaten** [pester/vscode-adapter#171]
https://github.com/pester/vscode-adapter/blob/7b21a036e075bc0855955f52b311740c7b4d9fd4/src/extension.ts#L46-L49

This tries to update `powershell.pester.suppressCodeLensNotice`, doesn't it? Should be `pester.suppressCodeLensNotice`

**Comment by JustinGrote** [comment]
@fflaten thanks! Probably a goof, as I recall it was working before. I'm finishing up a major change for multi-root workspace support and then I'll double check this after that.

**Comment by JustinGrote** [comment]
@fflaten thanks, I had a fire and forget on this so wasn't seeing the error that I was trying to update the powershell setting context and not the pester one. Fixed.
