### ISSUE TITLE
Need a extension setting for choosing what paths to use to list test

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#20]
When doing development for the repo [SqlServerDsc](https://github,com/dsccommunity/SqlServerDsc) we run 
```
.\build.ps1 -ResolveDependency -Tasks build
```

that gives us a folder structure like the following (just the important parts listed):

```
C:\source
└───SqlServerDsc
    │   build.ps1
    │
    ├───output
    │   └───RequiredModules
    │   └───SqlServerDsc
    ├───source
    │
    └───tests
        └───QA
                module.tests.ps1
        └───Unit
        └───Integration
```

In the folder _RequiredModules_ we have a lot of dependencies for the pipeline (among other things). The problem is that those modules in that folder contain a lot of tests that are also listed, but they are not part of the project.

The test from the red mark are not part of the SqlServerDsc project.
![image](https://user-images.githubusercontent.com/7189721/129045852-60d09e61-f3e5-43c1-afb0-9e623bb4945e.png)

Suggest adding a extension settings for setting what paths are used for reading tests, e.g. `ProjectTestFolders`.

**Comment by JustinGrote** [comment]
Thanks, this is on the to-do list after getting everything stable.

**Comment by johlju** [comment]
This works using the latest commit (https://github.com/pester/vscode-adapter/commit/6ffbaadfc491a5fb07a06c2746362e7e40e8488f) this now works perfectly 

```json
{
    "pester.testFilePath": [
        "[tT]ests/[uU]nit/*.[tT]ests.[pP][sS]1"
    ]
}
```

![image](https://user-images.githubusercontent.com/7189721/130605263-97d2feeb-b10a-4671-ad5b-20f20b5d561b.png)
