### ISSUE TITLE
If a test file have a parsing error the test explorer fails to expand the test

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#25]
If a test file contain a parsing error and then trying to expand the test file in the Test Explorer will result in it is not expanded with any error. Even after fixing the parsing error the test explorer can no longer expand that test file.

**Comment by JustinGrote** [comment]
Yes I currently don't surface test discovery errors well, this is a todo.

**Comment by JustinGrote** [comment]
I have some more work to do on the PR but it will basically look like this:
![image](https://user-images.githubusercontent.com/15258962/129986819-f63e9064-aafb-4377-8ffc-ecc2dffb32dc.png)

**Comment by johlju** [comment]
That looks great! Really cool so surface the actual error in test explorer too.

**Comment by JustinGrote** [comment]
Fixed in #39
