### ISSUE TITLE
Cannot run\discover tests when there are space characters in the path

### ISSUE THREAD

**Issue by Glober777** [pester/vscode-adapter#26]
Hi,

I've noticed that it if the path to my .Tests.ps1 files contain space characters. 

As far as I understand, the issue us caused by the fact that the path to the script file is provided to `PesterInterface.ps1` script without being wrapped into quotes, which leads the script to misinterpret the path value.

I'm not so good with TypeScript, but I think that the problem can be fixed here (by appending quotes on the both ends of `testLine`):
https://github.com/pester/vscode-adapter/blob/7007f6f5b5e66b2cd8087aad3e906d32cb8b7381/src/pesterTestController.ts#L247

**Comment by JustinGrote** [comment]
@Glober777 Thanks for the investigation! Should be simple enough to reproduce, I'll give it a shot and see if I can identify the issue.
