### ISSUE TITLE
♻️ Pester run pipeline

### ISSUE THREAD

**Issue by JustinGrote** [pester/vscode-adapter#28]
Firm up the Pester test types for the final API and optimize for async operations.

Primarily, Pester is not very efficient unless you run as many tests as you can together, so we want to take runhandler requests and queue them with a timer, and then execute once the timer expires

**Comment by box4443** [comment]
![ic_fluent_add_24_filled_dark](https://user-images.githubusercontent.com/106244400/170814947-868d03ba-28df-4ebb-b3d5-9958b94843e1.png)
![notificationsIcon](https://user-images.githubusercontent.com/106244400/170814953-103e3de1-aeff-41f4-b838-dbdc56c59881.png)
![syncIcon](https://user-images.githubusercontent.com/106244400/170814962-519f7d80-defc-4f78-980f-f215c6726c75.png)
![aboutIcon](https://user-images.githubusercontent.com/106244400/170814911-304f11ef-e37f-422c-944d-6cd8fc3d6ec8.png)
![accountIcon](https://user-images.githubusercontent.com/106244400/170814919-f8d3ae37-a593-4076-9206-2adae8affe26.png)
![chevronDown](https://user-images.githubusercontent.com/106244400/170814926-57b2197d-1642-44eb-93fa-a9ef882b95cc.png)
![chevronUp](https://user-images.githubusercontent.com/106244400/170814928-52905ff7-f630-45e9-844f-29b6034bc4d0.png)
![ic_fluent_add_24_filled](https://user-images.githubusercontent.com/106244400/170814933-7bb692d5-02d3-4f19-bc50-8da1e62f0489.png)
