### ISSUE TITLE
When saving a file the content in Test Explorer disappears can no longer be expanded

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#33]
![FoldingDisappeas](https://user-images.githubusercontent.com/7189721/129755568-dc993737-eb59-4b00-9596-0279774b17c1.gif)

**Comment by JustinGrote** [comment]
Thanks yeah I was aware of this but was having trouble reproducing it, it's probably something in the onDocumentUpdateHandler overwriting the test tree.

**Comment by JustinGrote** [comment]
This *might* be fixed with the implementation for #20, let me know if you still see it

**Comment by johlju** [comment]
This works perfectly now, when using (latest) commit https://github.com/pester/vscode-adapter/commit/6ffbaadfc491a5fb07a06c2746362e7e40e8488f.

Even handles a parsing error in the script file, and refreshes Test Explorer once the test script parses correctly. Awesome work!
