### ISSUE TITLE
A new setting to run a PowerShell command in the same process before first discovery

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#36]
When running tests in a PowerShell module project based on the [Sampler](https://github.com/gaelcolas/Sampler) project (or similar tools) there is a need to run `build.ps1` prior to running any tests. The `build.ps1` sets up the PowerShell session with the correct path to modules in `$env:PSModulePath` etc.

Suggest adding a setting that takes a path that is run the first time in each new session, before first discovery.

In our case the setting would hold `./build.ps1 -Task noop`

**Comment by johlju** [comment]
As a workaround now I need to run `./build.ps1 -Task noop` in the PowerShell Integrated Console prior to using Test Explorer. Maybe it possible to add that to a project specific `profile.ps1` though, not sure it is possible. Need to look into that.

**Comment by JustinGrote** [comment]
Yeah I'd say this is out of scope. If the build needs to be run prior to testing then you should have it checked and run during test discovery or in `BeforeAll {}`, you could also have a personal profile that dot-runs a build on startup.

I *may* add support for running a vscode task prior to Test Execution, but it is low priority. I'll leave it open for now.

**Comment by johlju** [comment]
I'm okay with closing this if you feel it still is out of scope down the road.

I can agree that this is more a setting for VS Code PowerShell extension to have the ability to run a profile.ps1 per project when starting PowerShell Integrated Console. There are ways to work around it, but that needs to be workedaround on each dev machine, would have been great to have a project setting so all contributors can get in when cloning.

**Comment by JustinGrote** [comment]
I don't see putting effort into this when it's better targeted as a vscode-powershell feature for the integrated console. I'd recommend opening it as an issue there.
