### ISSUE TITLE
How I can see test log from tests tree?

### ISSUE THREAD

**Issue by sergey-s-betke** [pester/vscode-adapter#46]
My example:

````powershell
Describe 'Open Document template' {
	Describe '<Name>' -ForEach @(
		$DestinationTemplateFile | Get-Item |
		ForEach-Object { @{ Name = $_.Name; FullName = $_.FullName } }
	) {
		It 'is valid (by ODFValidator)' {
			{
				java -D"file.encoding=UTF-8" -jar $ODFValidatorJarPath -e -w $FullName
				if ( $LASTEXITCODE -ne 0 )
				{
					Write-Error -Message 'Validation failed!' -ErrorAction 'Stop';
				};
			} | Should -Not -Throw
		}
	}
}
````

One test failed. How I can see test output from test tree?

**Comment by JustinGrote** [comment]
Test output is visible in the integrated console if you set your powershell extension run or debug verbosity preference. I also used to show it in the test result window but a last minute API change broke that part, I'm working on resolving it.

**Comment by sergey-s-betke** [comment]
@JustinGrote , ok, thank You!

And how i can set for this extension Pester run verbosity preference? And other Pester configuration params?

**Comment by JustinGrote** [comment]
> @JustinGrote , ok, thank You!
> 
> And how i can set for this extension Pester run verbosity preference? And other Pester configuration params?

https://code.visualstudio.com/docs/languages/powershell#_powershell-extension-settings

**Comment by JustinGrote** [comment]
Currently the extension inherits your settings from $PesterPreference. I plan to later add a config file to pick up other pester settings.

**Comment by sergey-s-betke** [comment]
> Currently the extension inherits your settings from $PesterPreference. I plan to later add a config file to pick up other pester settings.

Ok, thank You!
