### ISSUE TITLE
Pester Test Adapter should error if Pester is not Installed

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#54]
Trying to expand in test explorer and Pester is not available to the session makes that test no longer able to expand. When Pester is available (running `build.ps1` in this case) clicking on another test it tries to expands.

> Everything is a bit slow since I have the code on `/mnt/c`.

![FailsOnMissingPester](https://user-images.githubusercontent.com/7189721/130632586-43ba39be-2b5d-4542-b122-fc15ebef4d23.gif)

**Comment by johlju** [comment]
It would be nice it it could list the error thrown in the console "missing module Pester" as an error in the test explorer.

**Comment by JustinGrote** [comment]
The missing module pester shows in the terminal window and happens out-of-band of my pester process so I don't plan to fix this directly today, however in the future I will be implementing a dedicated process for test discovery and handling, and that process will be able to detect for Pester and throw a warning before registering the test controller.
