### ISSUE TITLE
Adapter won't work if path to VSCode has spaces.

### ISSUE THREAD

**Issue by wikiped** [pester/vscode-adapter#70]
Here is log from Pester Output panel:

```
22:08:11.248 INFO [dt.resolveHandler] Initializing Pester Test Controller and watching for Pester Files 
22:08:11.560 INFO [dt.watchWorkspaces] Detected Pester File:  d:\Temp\TestsWithPester\Tests\TestsWithPester.Tests.ps1 
22:08:17.008 DEBUG [undefined.<anonymous>] Run invoked on undiscovered testFile TestsWithPester.Tests.ps1, discovery will be run first 
22:08:17.012 DEBUG [dt.resolveHandler] Adding to Discovery Queue:  D:\TEMP\TESTSWITHPESTER\TESTS\TESTSWITHPESTER.TESTS.PS1 
22:08:17.118 INFO [dt.<anonymous>] Starting Test Discovery of 1 files 
22:08:17.144 INFO [dt.startPesterInterface] Starting PowerShell testing instance: C:\Program Files\PowerShell\7\pwsh.exe 
22:08:17.147 DEBUG [dt.startPesterInterface] Running Script in PS Worker: & 'D:\Visual Studio Code\data\extensions\pspester.pester-test-2021.9.1\Scripts\PesterInterface.ps1' -Discovery 'd:\Temp\TestsWithPester\Tests\TestsWithPester.Tests.ps1' 
```

It hangs after the last line and nothing (visible) happens.

<details><summary>Here is a capture from VSCode:</summary>
<p>

![Animation](https://user-images.githubusercontent.com/5990528/135729368-d09b06f5-a847-4458-8294-ee77ce229fdd.gif)

</p>
</details>

If I click on 'Run Pester Tests' in Context Menu of `TestsWithPester.Tests.ps1` Tab then tests are executed just fine without any output in Pester Panel.

Pester Tester v2021.9.1
Pester 5.3.1
Powershell Core 7.1.4

**Comment by JustinGrote** [comment]
Can you provide me your full TestsWithPester folder? You should be able to zip it and attach it here.

**Comment by JustinGrote** [comment]
What it looks like is that discovery is running but the actual test run is not happening.

**Comment by wikiped** [comment]
I have tried the simplest test file and the only one in folder:

```powershell
Describe 'Simple Test' {
    It 'Should pass' {
        $true | Should -BeTrue
    }
}
```

With the same result.

It might have something to do with the fact that I am using [portable VS Code installation](https://code.visualstudio.com/docs/editor/portable)..?

It obviously hangs and does not react to 'Cancel' button click or to integrated console restart.

VSCode has to be restarted (or folder closed) to cancel the hanging process.

**Comment by JustinGrote** [comment]
It's possible, the extension uses a relative path to find the powershellInterface script and maybe that is screwing up, I can test it in portable mode.

**Comment by JustinGrote** [comment]
Couldn't reproduce. This is vscode 1.6 stable with a data folder created, worked fine:
![image](https://user-images.githubusercontent.com/15258962/136115940-d746c6be-9f3e-4ca9-9a28-6175f9638388.png)

**Comment by wikiped** [comment]
Thanks for looking into it.

I also tried it on a clean installation of VSCode (with only Pester Adapter and Powershell Preview) and it did work.

So the problem is probably caused by another extension or perhaps settings?

If I will be able to narrow it down I will let know. 

Meanwhile feel free to close the issue.

**Comment by wikiped** [comment]
I have changed the title to reflect how I solved the problem:

Originally VSCode was installed in a portable mode in a folder called `Visual Studio Code`.

After it was renamed to `VisualStudioCode` (no spaces) the extension started to work.

So relative path or not - path did matter and since there was no issues with other extensions when there was space in path, it looks like there is a need to safeguard that spaces are not a problem.

Thanks.

**Comment by JustinGrote** [comment]
@wikiped thanks, I'll leave it open as a valid issue, I probably have some non-safe path somewhere.

**Comment by JustinGrote** [comment]
@wikiped sorry for the long delay, this should be fixed in the latest prerelease now.
`2023-07-19 09:53:26.177 [debug] Running Script in PS Worker: & 'C:\Users\jgrote\Downloads\VSCode With Spaces\data\extensions\pspester.pester-test-0.0.0-source\Scripts\PesterInterface.ps1' 'c:\Users\jgrote\Projects\vscode-adapter\sample\Tests\Basic.Tests.ps1:7'`
