### ISSUE TITLE
PesterInterface is not Set-Strictmode v3 Safe

### ISSUE THREAD

**Issue by JustinGrote** [pester/vscode-adapter#85]
`.IsRoot` tests may fail because not all objects it tests have `.IsRoot` as a property

**Comment by ziesemer** [comment]
This is unfortunately more than just an inconvenience.  I spent many hours trying to figure out why my tests were not working within the VSC Adapter but were otherwise working with `Invoke-Pester`.  Please consider that any code being sourced to place under test that includes setting strict mode will cause the tests to fail within VSC.

Here is a minimal test case:

	BeforeAll {
		Set-StrictMode -Version Latest
	}

	Describe 'Tests' {
		It 'Should-Pass' {
			# This test should pass.
		}
	}

**Comment by iRon7** [comment]
@JustinGrote,

Thanks for linking this case.

> as strictmode doesn't really provide much benefit other than a lot more annoying runtime errors

I don't fully agree with this statement as it has helped me quiet some time with revealing simple typo's. Besides (just) for my tests I prefer to be as strict as possible as others who do use my scripts might have this simply switched on (as what in fact happens here)...

**Comment by JustinGrote** [comment]
@iRon7 understood, I was just explaining why it is this way today, but I certainly underestimated the number of people using strictmode (as well as didn't think it would even matter due to the nature of how pesterinterface works).

**Comment by JustinGrote** [comment]
@iRon7 Can you test with the latest prerelease? I've run strict mode both in the Extension Terminal and in the standalone runner and your minimal test case now works fine.

**Comment by iRon7** [comment]
@JustinGrote,

> Can you test with the latest prerelease?

I will try to find sometime this coming weekend.

**Comment by ziesemer** [comment]
From my perspective - both with the [minimal test case included above](https://github.com/pester/vscode-adapter/issues/85#issuecomment-987545191), and with the tests that I've previously referenced at https://github.com/ziesemer/ad-privileged-audit/ - this is now working perfectly.  Thank you!

**Comment by JustinGrote** [comment]
Glad to hear, will close but can reopen if a test case comes up that doesnt work.

**Comment by iRon7** [comment]
Confirmed: prerelease version `v2023.6.2` works fine now.
Thanks for the efforts
