### ISSUE TITLE
Is there a way to change the startup directory for the PowerShell process?

### ISSUE THREAD

**Issue by lujomu** [pester/vscode-adapter#89]
It seems the current startup directory is the VSCode app directory (`$Env:LocalAppData\Programs\Microsoft VS Code` in Windows). Is there a way to set it, for example, to the VSCode workspace folder (`${workspaceFolder}`)?

I know there is `$PSScriptRoot` to reference the current test file's directory, but there seems to be no straight forward/consistent way to reference the workspace root (directory).

**Comment by JustinGrote** [comment]
I can look into enabling it to follow wherever you have PSIC defined or a separate setting, but `$PSScriptRoot` is indeed the recommended way to reference relative paths in tests.

**Comment by lujomu** [comment]
The PSIC cwd is a great idea! That way the behavior would be consistent with the PowerShell extension's run/debug commands.

**Comment by JustinGrote** [comment]
This was fixed a while ago in c3cb336
