### ISSUE TITLE
Feature Request: Add a "Pause" Button in Test Explorer bar

### ISSUE THREAD

**Issue by alta4096** [pester/vscode-adapter#93]
Hi,
Thanks a lot for this great extension.
I think it would be practical to add a "Pause" button that will stop discovery, stop autorun on save.
Even if there is the setting pester.autoRunOnsave , this button will allow more dynamic interaction between code change and tests Runs.

My scenario is that during the conversion of pester v4 to pester v5 , this extension run the v4 tests and I would prefer to pause theses tests during the conversion time.
Thank you for your time on this.
![image](https://user-images.githubusercontent.com/39650771/149127007-51a5b4cf-d1f0-49da-8d9e-15f2762c8c08.png)

**Comment by JustinGrote** [comment]
Thanks, I'll consider after I get done with the pipeline refactor. Just an FYI Pester 4 isn't supported, it should fail unless you run Pester 5.

**Comment by JustinGrote** [comment]
I'm gonna block this one on https://github.com/microsoft/vscode/issues/134941 so that I'm not reinventing the wheel.

**Comment by JustinGrote** [comment]
Implemented in #96

**Comment by alta4096** [comment]
Thank you so much. That's excellent.
