### ISSUE TITLE
Disabling the Pester CodeLens does not work for workspace

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#94]
When clicking Workspace Only in this dialog there are no changes in the workspace settings.json.

![image](https://user-images.githubusercontent.com/7189721/150297581-297c90ac-68cd-4022-a86b-8ea8b6a3409b.png)

Expected it to add the following to the workspace settings JSON.
```json
{
    "powershell.pester.codeLens": false
}
```

**Comment by JustinGrote** [comment]
Simple bug, should work in next release, sorry about that.
